"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 1.11.12.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'w#9zsgdla5(-wu$f))*x=b*a6c+7uhf#8)(v0(7xjirfd#@u(!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'polls.apps.PollsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ols',
        'USER': 'root',
        'PASSWORD': '020497',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Fortaleza'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/assets/'


STATICFILES_DIRS = [
    '/../polls/static/assets/css/main.css',
    '/../polls/static/assets/css/ie8.css',
    '/../polls/static/assets/css/ie9.css',
    '/../polls/static/assets/js/ie/html5shiv.js',
    '/../polls/static/assets/js/jslogin.js',
    '/../polls/static/assets/images/pic01.jpg',
    '/../polls/static/assets/images/pic02.jpg',
    '/../polls/static/assets/images/pic03.jpg',
    '/../polls/static/assets/images/pic04.jpg',
    '/../polls/static/assets/images/pic05.jpg',
    '/../polls/static/assets/images/pic06.jpg',
    '/../polls/static/assets/images/pic07.jpg',
    '/../polls/static/assets/images/pic08.jpg',
    '/../polls/static/assets/images/pic09.jpg',
    '/../polls/static/assets/images/pic10.jpg',
    '/../polls/static/assets/images/pic11.jpg',
    '/../polls/static/assets/images/select-arrow.jpg',
    '/../polls/static/assets/images/icone.jpg',
    '/../polls/static/assets/images/icon.png',
    '/../polls/static/assets/images/bg.jpg',
    '/../polls/static/assets/css/demo.css',
    '/../polls/static/assets/css/csslogin.css',
    '/../polls/static/assets/css/style.css',
]

LOGIN_URL='/login/'
LOGOUT_URL='/logout/'
LOGIN_REDIRECT_URL='polls:index'
