# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 19:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_book', models.CharField(default=b'', max_length=100)),
                ('author_book', models.CharField(default=b'', max_length=100)),
                ('subject_matter', models.CharField(default=b'', max_length=100)),
                ('year', models.IntegerField()),
                ('edition', models.CharField(default=b'', max_length=10)),
                ('publishing_company', models.CharField(default=b'', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Devolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_devolution', models.CharField(default=b'', max_length=10)),
                ('book_loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=b'', max_length=14)),
                ('password_librarian', models.CharField(default=b'', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_loan', models.CharField(default=b'', max_length=10)),
                ('data_devolution', models.CharField(default=b'', max_length=10)),
                ('book_rented', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Book')),
                ('user_librarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Librarian')),
            ],
        ),
        migrations.CreateModel(
            name='Renovation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_renovation', models.CharField(default=b'', max_length=10)),
                ('date_shelf_life', models.CharField(default=b'', max_length=10)),
                ('book_renovation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserve', models.CharField(default=b'', max_length=10)),
                ('data_shelf_life', models.CharField(default=b'', max_length=10)),
                ('book_reserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.IntegerField()),
                ('password_student', models.CharField(default=b'', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_usr', models.CharField(default=b'', max_length=100)),
                ('cpf_usr', models.CharField(default=b'', max_length=11)),
                ('email', models.CharField(default=b'', max_length=50)),
                ('street', models.CharField(default=b'', max_length=255)),
                ('number', models.IntegerField()),
                ('phone', models.CharField(default=b'', max_length=14)),
                ('postcard', models.CharField(default=b'', max_length=10)),
                ('city', models.CharField(default=b'', max_length=50)),
                ('state', models.CharField(default=b'', max_length=20)),
                ('neighborhood', models.CharField(default=b'', max_length=50)),
                ('birth', models.CharField(default=b'', max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='user_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Usuario'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='user_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Student'),
        ),
        migrations.AddField(
            model_name='renovation',
            name='user_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Student'),
        ),
        migrations.AddField(
            model_name='loan',
            name='user_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Student'),
        ),
        migrations.AddField(
            model_name='librarian',
            name='user_librarian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Usuario'),
        ),
        migrations.AddField(
            model_name='devolution',
            name='user_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Student'),
        ),
    ]
